name: PHP Validation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: world
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: pdo, pdo_mysql

    - name: Verify MySQL connection
      run: |
        mysql --version
        mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES"

    - name: Import test database
      run: mysql --host 127.0.0.1 --port 3306 -uroot world < world.sql

    - name: Check PHP syntax
      run: |
        php -l world.php
        php -l index.html

    - name: Start PHP server
      run: php -S localhost:8000 &

    - name: Test PHP endpoints
      run: |
        curl "http://localhost:8000/world.php?country=Jamaica"
        curl "http://localhost:8000/world.php?all=true"
